#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#spring:
#  application:
#    name: Job_POC
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
 
  
  
  
  